### ISSUE TITLE
Priorities/Roadmap for KPS4_3L

### ISSUE THREAD

**Issue by 1-Bart-1** [ufechner7/KiteModels.jl#103]
- [ ] Fast constrained initialization for good tether state estimation.
- [ ] Control kite using NMPC with stiff solver
- [ ] Control kite using KiteControllers.jl

**Comment by ufechner7** [comment]
Kite control is not in the scope of this package.

**Comment by 1-Bart-1** [comment]
Closing this as it is completed
